name: imc
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - numpy
  - scipy
  - sympy
  - pandas
  - jupyter
  - pip
  - gfortran
  - doxygen
  - graphviz
  - ghp-import